name: OWASP ZAP Full Scan

on:
  workflow_run:
    workflows: ["Continuous Deployment"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: OWASP ZAP Fullscan
      uses: zaproxy/action-full-scan@v0.3.0
      with:
        target: 'https://www.weak-snake-93.a276.dcdg.xyz/'
