name: OWASP ZAP Full Scan

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy app
      uses: zaproxy/action-full-scan@v0.3.0
      with:
        target: '0.0.0.0:5000'
